version: '3.4'

services:
  accountmanager.api:
    image: accountmanager-api
    container_name: accountmanager-api
    build:
      context: .
      dockerfile: src/AccountManager.Api/Dockerfile

  accountmanger.db:
    image: mysql
    container_name: accountmanager-mysqldb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: AccountManager
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
